### ISSUE TITLE
YUNG's Better Caves will make the dungeon generation incomplete

### ISSUE THREAD

**Issue by Dr-WeiAL** [xyroc/DungeonCrawl#100]
![2021-10-29_07 37 51](https://user-images.githubusercontent.com/47446553/139350731-442a699e-38a3-4f90-9dec-4a466ca4e236.png)
![2021-10-29_07 38 28](https://user-images.githubusercontent.com/47446553/139350738-2e1390a4-975e-406b-916f-88e0f33c3af0.png)
Is this a known issue?

**Comment by Loewetiger** [comment]
This is intended behavior, you can change it by setting `solid = true` in the `dungeon_crawl.toml`.

**Comment by Dr-WeiAL** [comment]
> This is intended behavior, you can change it by setting in the .`solid = true``dungeon_crawl.toml`

okay, thank you
