### ISSUE TITLE
DungeonCrawl-1.16.5-2.3.3 Mod loading error has occurred / Mod loading has failed

### ISSUE THREAD

**Issue by Thombias** [xyroc/DungeonCrawl#101]
Getting this nasty crash which prevents me from loading my modpack. I tried resetting the config but that didn't work. Went back to mod version 2.3.2 which loads the game just fine.

Crash log here:
[crash-2021-11-07_16.45.23-fml.txt](https://github.com/xyroc/DungeonCrawl/files/7492581/crash-2021-11-07_16.45.23-fml.txt)

**Comment by xyroc** [comment]
Looks like CaveBiomeApi has introduced a compatibility module for Dungeon Crawl which broke with version 2.3.3. Their github does not seem to be up to date though, so its hard to tell what exactly it is.

**Comment by Thombias** [comment]
Should i report this compatibility issue on their Github then?
I reported it here because i'm not a modder and not quite capable of understanding/reading crash reports, so my mind just went "DungeonCrawl 2.3.3 doesn't work but 2.3.2 works so it can only be that mod"

**Comment by xyroc** [comment]
Yeah, I would report it on their Github and see what they say.

**Comment by ItsBlackGear** [comment]
ok! i found why it isn't working anymore.

DungeonCrawler used to have this piece of code which caused some issues in CBA
```java
    @Override
    protected boolean isFeatureChunk(ChunkGenerator p_230363_1_, BiomeProvider p_230363_2_, long p_230363_3_, SharedSeedRandom p_230363_5_, int p_230363_6_, int p_230363_7_, Biome p_230363_8_, ChunkPos p_230363_9_, NoFeatureConfig p_230363_10_) {
        for (Biome biome : p_230363_2_.getBiomesWithin(p_230363_6_ * 16, p_230363_1_.getSpawnHeight(), p_230363_7_ * 16, 64)) {
            if (!biome.getGenerationSettings().isValidStart(this))
                return false;
        }
        return true;
    }
```
so i'm not entirely sure if removing the mixin will make it generate as it should, but i'll be testing it

**Comment by ItsBlackGear** [comment]
confirmed, getting rid of that mixin allows the dungeons to generate
![imagen](https://user-images.githubusercontent.com/68313143/140673030-fcc45113-1d67-4301-af4f-1539624f8854.png)
a new update will come soon

**Comment by ItsBlackGear** [comment]
uhh friendly reminder that the issue has been fixed and this can be closed 👀

**Comment by Thombias** [comment]
Ah yeah, doing that now. Thanks for reminding. :)
