### ISSUE TITLE
Dungeon generation does not work in BIOMES O PLENTY

### ISSUE THREAD

**Issue by quakeman00** [xyroc/DungeonCrawl#107]
custom structures like waystones / quark / mo shiz / productive bees do generate in a biomesoplenty world gen but the dungeons does not

**Comment by LordCodFish** [comment]
> 

I'm also having the same issue.  Installed dungeoncrawl, valhelsia, and a few others- none of them are working with biomesoplenty..

**Comment by dduttton** [comment]
Same issue here. Have biomes o plenty installed on 1.18.1 and have traveled about 6000 blocks in every direction. No dungeons.
