### ISSUE TITLE
Hell Stage not generating in 1.18

### ISSUE THREAD

**Issue by WelliWat** [xyroc/DungeonCrawl#108]
For some reason the hell stage (fifth floor) is not generating in the 1.18 version. I noticed that a couple of other people commented about this over on CurseForge.

**Comment by wnbrn** [comment]
I'm playing on 1.16.5 and the hell stage doesn't spawn either. I thought it would be due to 1.18 and the extended height limits however it seems that isn't the case.

**Comment by iamcarrotmaster** [comment]
I'm having the same issue, 1.18.1

**Comment by jjlrjjlr** [comment]
Same issue, also in 1.18.1.

**Comment by clarence112** [comment]
Same issue, 1.18.1
