### ISSUE TITLE
Dungeon Crawl Unable To Load

### ISSUE THREAD

**Issue by ChelseyBionix** [xyroc/DungeonCrawl#113]
im playing on a modded 1.18.1 server ( im on tlauncher ) and whenever i try and open it it shows this
<img width="445" alt="mc" src="https://user-images.githubusercontent.com/98659539/151670671-3ebb6340-6f2c-4ede-9d7d-5158e377e363.png">

**Comment by xyroc** [comment]
What other mods are you using?

**Comment by ChelseyBionix** [comment]
it started working nvm
