### ISSUE TITLE
Failed to load correctly (1.18.2)

### ISSUE THREAD

**Issue by vKILLZONEv** [xyroc/DungeonCrawl#117]
I'm trying to add this mod to a 1.18.2 modpack and I'm getting a failed to load error even with no other mods included.  Here's the log:

[crash-2022-03-17_16.28.40-fml.txt](https://github.com/xyroc/DungeonCrawl/files/8291590/crash-2022-03-17_16.28.40-fml.txt)

Forge version 40.0.17

**Comment by Charmanth** [comment]
According to the curseforge file version, it's only for 1.18.1, you'd have to wait for a dev to update to 1.18.2
