### ISSUE TITLE
[Bug] Pregenerated structures get cut in half

### ISSUE THREAD

**Issue by Pendrag00n** [xyroc/DungeonCrawl#127]
When I pregenerate a world using chunky, structures get cut in half between chunks. This only happens with this mod.

I'm running a Forge 40.1.31 server and I'm using the following modlist:
https://pastebin.com/raw/fj0e0Ru3

![1](https://user-images.githubusercontent.com/88731722/173238981-76c7a32a-32df-4a1f-9b9e-fd13d7ded543.png)
![2](https://user-images.githubusercontent.com/88731722/173238986-6e00a034-4277-4259-a66f-a412eed59ff8.png)
![3](https://user-images.githubusercontent.com/88731722/173238994-62d87c94-5ffe-4d02-ab8c-2f5a756d0ce2.png)
![4](https://user-images.githubusercontent.com/88731722/173238996-9c036739-ebaf-450d-99b5-e1666feb8355.png)

**Comment by xyroc** [comment]
This will be fixed in version 2.3.9
