### ISSUE TITLE
[1.18.2] Crash on world creation

### ISSUE THREAD

**Issue by aking4125** [xyroc/DungeonCrawl#129]
Hello, Upon creating a new world. The game crashes with the following crash report:
[crash-2022-06-24_02.44.35-client.txt](https://github.com/xyroc/DungeonCrawl/files/8973808/crash-2022-06-24_02.44.35-client.txt)
 
 Any ideas?

**Comment by xyroc** [comment]
Looks like the default datapack wasn't loaded properly. Could you share the full log?

**Comment by Mai-xiyu** [comment]
Hello, Lead Developer, sorry to bother you
Can you allow me to post your mods to Minecraft in China, of course, all rights are yours
