### ISSUE TITLE
[1.19] Crash upon creating world

### ISSUE THREAD

**Issue by radiogagaexe** [xyroc/DungeonCrawl#130]
I initially commented on CurseForge but realised I should have reported it here instead.

My game crashes every time I try to create a new world.

When I attempt to open an already created world, I get the error "Errors in currently selected datapacks prevented the world from loading. You can either try to load it with only the vanilla data pack ("safe mode") or go back to the title screen to manually fix it"
I am using Forge 41.0.98

Here is the full crash report:
[crash-2022-07-14_22.10.16-client.txt](https://github.com/xyroc/DungeonCrawl/files/9111614/crash-2022-07-14_22.10.16-client.txt)

**Comment by xyroc** [comment]
This is most likely due to forge's breaking changes in version 41.0.94. I will fix this soon.

**Comment by xyroc** [comment]
Fixed in version 2.3.11

**Comment by radiogagaexe** [comment]
Thank you so much! Looking forward to playing this mod :D
