### ISSUE TITLE
[1.16.5] Rendering Entity Spawner Crash with Shaders

### ISSUE THREAD

**Issue by BlueDrakon1** [xyroc/DungeonCrawl#135]
I'm currently making a modpack and for some reason, it seems that when I use shaders, only the spawners from this mod seem to crash my game. I will say, the modpack I am making is a (very) large one so it could be because of a combination of mods, but I have noticed that it only happens with Dungeon Crawl dungeons and in combination with shaders. I am unsure why, if someone may be able to help me figure out how to fix it or what's causing it. I thought it might be an error with Epic Fight mod, but again, any other spawners work perfectly fine with the epic fight models.

[crash-2022-11-09_20.34.54-client.txt](https://github.com/xyroc/DungeonCrawl/files/9978606/crash-2022-11-09_20.34.54-client.txt)

**Comment by xyroc** [comment]
This is likely an issue with the epic fight mod. The problem seems to occur while rendering the armor of the entity in the spawner, and since most other spawners don't have armored mobs, it doesn't happen with those.

**Comment by BlueDrakon1** [comment]
> l

Alright, that makes more sense, thank you. I'm going to try to see if there's a solution. Does the "Whether custom mob spawners with equipment, etc.. should be used" config make it so that the mobs in the dungeon are unarmored or make just the spawners appear unarmored? I changed up the config for Epic Knights (Not Epic Fight) so that the armor from that mod doesn't override the equipment in Dungeon Crawl, maybe that will help?
