### ISSUE TITLE
1.18.2 dungeons not solid

### ISSUE THREAD

**Issue by CharleeToombs** [xyroc/DungeonCrawl#136]
Hello!

I've set the config option: 
# Makes the entire dungeon solid, preventing caves, ravines, etc... from interfering with the dungeon.
	#
	solid = true
And still have massive holes all around and in the floor, is that as intended? my hope was to make them encased.

**Comment by xyroc** [comment]
Are you sure you were looking at a dungeon that was generated after the change? I would create a new world just to be sure.
