### ISSUE TITLE
[1.20.1] DungeonCrawl spawners revert to original state after spawning a mob or two if changed by a spawn egg.

### ISSUE THREAD

**Issue by Luviam** [xyroc/DungeonCrawl#151]
https://github.com/xyroc/DungeonCrawl/assets/56097409/55433422-1e23-46a9-8878-51f2283c377a

Forge 47.2.0

Modlist:
Dungeon Crawl

**Comment by xyroc** [comment]
Hey, this is not actually a bug. This mod creates spawners with multiple entities which are chosen randomly from. The default is six different entities per spawner. So, when you click the spawner with a spawn egg, you only overwrite one of the six entities.
You can change the amount of different entities per spawner by altering the value of `spawner_entities` in the config file.
