### ISSUE TITLE
[Help] Wanting to change the spawn radious of Dungeons

### ISSUE THREAD

**Issue by 5tratz** [xyroc/DungeonCrawl#152]
Hi, I am currently using 1.20.1 version and I no longer see the options (min and max) spacing of the dungeons to spawn. I want to make them spawn rarely instead of often, I used to have this set well on the 1.19.2 version and it worked, but the configs for the spacing/spawn distance is no longer in the later versions.

Can you tell me what lines I need to edit please so I can change the spawn distance to be rare.

Thanks

**Comment by xyroc** [comment]
Hi, sadly it is no longer possible to adjust the placement settings through the config file. Instead, you will have to use a datapack ([Here is a premade one for this made by Nachtflame](https://cdn.discordapp.com/attachments/616766787966599172/1134335237288099890/DungeonCrawl-Adjuster.zip?ex=65a9f483&is=65977f83&hm=ba290e7ff6f776a716c656acd2fa2d2dc7c8a16b66563e96edd7ee9693340397&)).
In the datapack, navigate to the file `data/dungeoncrawl/worldgen/structure_set/dungeons.json` and edit the `spacing` and `separation` values in there. Be careful to not mess up the json format though, only edit the numbers, do not delete any commas etc.
