### ISSUE TITLE
Is there a way to generate dungeons in a specific place in the overworld?

### ISSUE THREAD

**Issue by KeruMx** [xyroc/DungeonCrawl#155]
Is there a way to generate dungeons in a specific place in the overworld?

_Originally posted by @KeruMx in https://github.com/xyroc/DungeonCrawl/issues/59#issuecomment-2175647536_

**Comment by xyroc** [comment]
Yes, you can use the vanilla `/place` command for that. To generate a dungeon at your current position, use `/place structure dungeoncrawl:dungeon ~ ~ ~`.
