### ISSUE TITLE
I am finding no loot in most of the chests

### ISSUE THREAD

**Issue by PlatinumBoi03** [xyroc/DungeonCrawl#159]
This started happening yesterday. On the first level, only one chest had loot and I am writing this as I play the mod now and the second level also has no loot.

**Comment by xyroc** [comment]
Weird. Are you getting any errors in the logs when loading into a world / reloading the data packs?

**Comment by PlatinumBoi03** [comment]
No. The mod was fine the last time I used it. Here is the log
[latest.log](https://github.com/user-attachments/files/17624192/latest.log)

**Comment by xyroc** [comment]
Actually it looks like Dungeon Crawl is missing in your installation. The mod was installed before but isn't anymore.
