### ISSUE TITLE
[1.14.4] [Singleplayer] Client crash on 'createLootRoom' function generating new chunk

### ISSUE THREAD

**Issue by dreckz** [xyroc/DungeonCrawl#16]
Forge: **28.2.0**
MC: **1.14.4**
DungeonCrawler Version: **DungeonCrawl-1.14.4-1.6.2**

Upon entering a new chunk it crashed attempting to create a loot room.  

However,  this was not the case 100% of the time because I was able to generate new chunks fast with the dungeons and it seemed that this specific one did that.  Not sure if just a rare bug, but it didn't happen all the time.

Thanks for the recent update!

Crashlog:
[crash-2020-02-15_13.22.07-server.txt](https://github.com/XYROC/DungeonCrawl/files/4208928/crash-2020-02-15_13.22.07-server.txt)

**Comment by dreckz** [comment]
Additionally, I tried loading up a new world, but it got stuck at 12% and I check the logs and it looks like an identical crash:
Line: 4176 - 4251
[latest.log](https://github.com/XYROC/DungeonCrawl/files/4208935/latest.log)

**Comment by xyroc** [comment]
Alright, that should be fixed now.
