### ISSUE TITLE
Dungeons Ignoring Overworld Blacklist

### ISSUE THREAD

**Issue by Omnimetatron** [xyroc/DungeonCrawl#18]
Using this config: https://pastebin.com/cRGe6nSt dungeons are being spawned in minecraft:lukewarm_ocean ignoring the blacklist. Pictures can be provided.

**Comment by xyroc** [comment]
Is this happening in 1.14 or 1.15? Also which version of the mod do you use?

**Comment by Omnimetatron** [comment]
DungeonCrawl-1.15.2-1.6.2

**Comment by TheUntamed** [comment]
Where do I find the blacklist? The _dungeon_crawl.toml_ mentions it and allows to disable it, but doesn't contain a list to be edited.

**Comment by xyroc** [comment]
The list is in the config.json file in of the DungeonCrawl folder.

**Comment by TheUntamed** [comment]
hm ok. Found it and the biomes I wanted to blacklist (ocean, deep_ocean) are already blacklisted.
Using TerraForged World generation seems to break this. I already asked the people from Terraforeged and they said the biome ids are the same ("minecraft:ocean" and "minecraft:deep_ocean").
