### ISSUE TITLE
[1.15.2]Dungeons do not form

### ISSUE THREAD

**Issue by EnterFor** [xyroc/DungeonCrawl#21]
I joined this Mod halfway through
Need to create a new world?
The configuration file has been modified: dungeon_probability = 1.0
I am Chinese, I don't know if you can understand

**Comment by xyroc** [comment]
You don't need to create a new world as long as you explore new areas, Further, the dungeons don't spawn in or near certain biomes such as oceans, so you might just have been unlucky.
Also please tell me the seed of the world.

**Comment by EnterFor** [comment]
Seed: [-493816124572792915]
I was pretty sure I wouldn't get out of the dungeon
I've now deleted the Mod for the time being

**Comment by EnterFor** [comment]
Sorry, machine translation, I don't know if you understand
I'm Chinese
