### ISSUE TITLE
[1.15.2]Server crash

### ISSUE THREAD

**Issue by EnterFor** [xyroc/DungeonCrawl#23]
[crash-2020-03-17_22.33.10-server.txt](https://github.com/XYROC/DungeonCrawl/files/4343973/crash-2020-03-17_22.33.10-server.txt)
[debug.log](https://github.com/XYROC/DungeonCrawl/files/4343974/debug.log)

Strangely, I have not installed this Mod

But show this Mod information in line 8144 of debug.log?

Is that the problem?

**Comment by xyroc** [comment]
That is the problem. You've created a world with the mod and then uninstalled it.

**Comment by EnterFor** [comment]
> 那就是问题所在。您已经使用mod创建了一个世界，然后将其卸载。

I installed it again and the problem was solved.
This can be tricky if someone wants to delete it.
