### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Ake247** [xyroc/DungeonCrawl#24]
Can the final level be configured to be made of the overworld materials? or even made of just nether brick or obsidian because It seems worthless to go to the nether (within reason, of course, IE glowstone and quartz) once you complete the dungeon.

**Comment by xyroc** [comment]
Yes, I will add that.

**Comment by Ake247** [comment]
Another suggestion if possible is to add a configuration for preferred room generation. I have seen some with the library and some without and the ones with are so much better.
