### ISSUE TITLE
Is there a way to open a map generated with your mod in vanilla?

### ISSUE THREAD

**Issue by AndreiTS** [xyroc/DungeonCrawl#26]
I tried that but the world got corrupted

**Comment by xyroc** [comment]
Not really. Maybe if you can mange to remove all dungeon crawl structures from the save ( I dont know how to do that). You will still need to provide the loot tables through a separate datapack though.

**Comment by AndreiTS** [comment]
I deleted all region files that had a dungeon and it worked
