### ISSUE TITLE
Bottom Netherblock Layer

### ISSUE THREAD

**Issue by TheUntamed** [xyroc/DungeonCrawl#27]
Sometimes the bottom layer of a dungeon is made of Netherbricks, Obsidian and Magmablocks. Is it possible to disable that? Because for a progression based modpack it might be unpractical if it's possible to have access to those blocks without entering the Nether.

It would also be cool if it's possible to design the layers based on the dimension.
So that Dungeons in the Overworld are made of Overworld blocks and Dungeons in the Nether are made of Nether materials.

**Comment by xyroc** [comment]
Yes, it will be possible to disable nether content in the next update.
