### ISSUE TITLE
[SUGGESTION] Standard 'Nilla format for LootTables

### ISSUE THREAD

**Issue by Nachtflame** [xyroc/DungeonCrawl#3]
Is there any chance you could rework your loot-tables to follow the vanilla format internally?  Currently, with the change to custom-formatted tables in the config folder,  I cannot find any way to add an entry that references another loot_table (which I could do using vanilla datapacks before the change).

Specific use example:
TreasureBags by SilentChaos512, uses datapacks for setting up all the bags, loot for them, etc.  He's also setup a function that allows for designating them in Loot Tables.  With your current formatting there is no way to add these bags to your loot_tables (as they need the proper *type* .nbt added by the function).

**Comment by xyroc** [comment]
Coming in update 1.5.0 :)
