### ISSUE TITLE
Dungeon generation is really weird

### ISSUE THREAD

**Issue by traveldesign** [xyroc/DungeonCrawl#34]
So I just installed the mod for 1.16.1. It generates the dungeons but in a very random way. Sometimes when I use the /locate command it says it can't find any within reasonable distance. Then, as I'm exploring, I'll come across a whole bunch in the same area. Here's a screenshot of my map that has 3 in the same place. In another part of my map there were 5 in the same small biome. I'm using BoP also.
![2020-07-24_18 27 52](https://user-images.githubusercontent.com/60497291/88460076-3f73f380-ce5f-11ea-8a9a-0e2fef8e3cfa.png)
Any ideas of what I should do?

**Comment by Chemalagos** [comment]
I have the same issue, + dungeons just generate in tiny coords, no more from 500,500
