### ISSUE TITLE
[1.16.1 - Suggestion] Add a config option that "encases" dungeons for cave generation compatibility 

### ISSUE THREAD

**Issue by pa1nki113r** [xyroc/DungeonCrawl#38]
Throughout a newly generated world I'm testing with a personal modpack, I noticed that the dungeons are essentially being "ripped up" due to cave generation overhaul mods such as Yung's Better Caves for Minecraft 1.16. Would it be possible to add an option somehow to prevent the dungeons from being torn apart by generated caves?

**Comment by Enethim** [comment]
Is this fixed yet in newer versions ?
