### ISSUE TITLE
[QUESTION] Configuring loot tables with items from other mods

### ISSUE THREAD

**Issue by FiskFuji** [xyroc/DungeonCrawl#4]
Hi there,

I have a question regarding using the config files to insert other mods' items into the dungeons server side. For example, I edit loot.json, and add the following entry to `chest_stage_1.entries`:
`{
  "resourceName": "silentgems:opal",
  "min": 1,
  "max": 3,
  "weight": 2
}`

I add this to both my client config and my server config, yet it crashes with a NullPointerException (throws NullPointerException: Feature placement). This is the only change I made to the configs. I tried different mods as well but they result in the same crash. Below is a pastebin of the log:
https://pastebin.com/TAUN7pLv

Is this feature not supported with the current version of the mod, or am I doing something wrong?

Thanks!

**Comment by xyroc** [comment]
You are doing everything right and using items from other mods should be possible. There seems to be an error though but that does not matter anyway because I will switch back to vanilla loot tables in the next update. That should resolve the issue.
