### ISSUE TITLE
[1.16.1] datapack customizations not following loot_levels in random_item function

### ISSUE THREAD

**Issue by ahinh43** [xyroc/DungeonCrawl#41]
I'm trying to customize the loot tables using the Datapack customization page on this repo's wiki (https://github.com/XYROC/DungeonCrawl/wiki/Datapack-Customization) and I've noticed that ever since I loaded the datapack with the modified loot tables the extra items I've placed in the data/dungeoncrawl/loot_tables/chests/*.json files were loaded correctly but items generated by dungeoncrawl:random_item only followed the data/dungeoncrawl/treasure/stage_1.json file and ignored the value set in the configuration file. 

Here's a section of my data/dungeoncrawl/loot_tables/chests/treasure_room.json file:
![image](https://user-images.githubusercontent.com/14356001/93038272-29d2ad00-f60a-11ea-8d15-07078c0818d8.png)

Aside from some extra items I added in the loot_tables/chests files (which generate just fine) I just used the configuration listed in these areas in the repo to fill in the rest.

https://github.com/XYROC/DungeonCrawl/tree/1.15/src/main/resources/data/dungeoncrawl/loot_tables/chests

https://github.com/XYROC/DungeonCrawl/tree/1.15/src/main/resources/data/dungeoncrawl/treasure

Based on what the wiki tells me, I should expect stage_5.json to be used for the random item generation which would load a portion of the chest with iron and diamond items. Instead I get leather, wood, and other early game items in the chest with very weak enchantments. 

Additionally, the enchanted_book function faces a similar issue where the loot_level is set to 5, but the enchants the book generates with are very weak enchantments (like power 1). 

To further test this, I changed my data/dungeoncrawl/treasure/stage_1.json file to only generate diamond ores. After applying the change and reloading my world, my treasure room chests start generating with diamond ores instead of the early game equipment it normally gives, which helps confirm my suspicions. 

I am not sure if this is an actual bug or if I did something wrong in my datapack as this is the first time I'm creating one for my world. Any input is appreciated.

Thanks!

**Comment by xyroc** [comment]
Bit of a late answer, but cause of the issue you are having is that the "loot_level" parameter needs to be called "stage" in version 2.0.x. This has been changed in 2.1.x to "loot_level", which you are currently using. Therefore, updating dungeon crawl should fix it!
