### ISSUE TITLE
[1.16.3-2.1.1] Instead of mob spawners there are stone blocks in dungeons.

### ISSUE THREAD

**Issue by Thombias** [xyroc/DungeonCrawl#49]
Minecraft Version: 1.16.3
Forge Version: forge-34.1.25
Mod Version: DungeonCrawl-1.16.3-2.1.1

So, whenever there's supposed to be a mob spawner, there's in 95% of the cases a single stone block in its place. The dungeons only very rarily ever have mob spawners in them. I tried removing YUNG's better caves to see if the stone blocks instead of mob spawners were caused by it, but they were still present. I also tried setting the "solid" config option to true, but that also didn't fix it. I left everything else at default settings.

I have a lot of mods installed, as i'm currently working on a modpack, maybe one of those mods is causing the issue. I left all mod configs at default values. Anyway, here's my mod list (It's a lot, beware) : 

  | [FORGE] Iron Furnaces | XenoMustache | ironfurnaces-1.16.3-2.4.0.jar |  
  | Additional Banners | DarkhaxDev | AdditionalBanners-1.16.3-4.0.1.jar |  
  | Advanced Mining Dimension | henkelmax | mining_dimension-1.16.3-1.0.5.jar |  
  | Areas | Serilum | areas_1.16.3-1.1.jar |  
  | AutoFish for Forge | northwestwindnff | forgeautofish-1.0.5-1.16.3.jar |  
  | AutoRegLib | Vazkii | AutoRegLib-1.6-46.jar |  
  | Backpacked | MrCrayfish | backpacked-1.6.1-1.16.3.jar |  
  | Backpacker | MrCrayfish | backpacker-1.0.0-1.16.3.jar |  
  | Basalt Blocks | Legopitstop | BasaltBlocks-1.16.3-1.0.0.jar |  
  | Bedspreads (Forge) | TheIllusiveC4 | bedspreads-forge-1.16.3-5.0.0.1.jar |  
  | Better Burning | DarkhaxDev | BetterBurning-1.16.3-4.0.2.jar |  
  | Bookshelf | DarkhaxDev | Bookshelf-1.16.3-8.7.20.jar |  
  | BountifulBaubles | Cursed1nferno | Bountiful Baubles FORGE-1.16.3-0.0.2.jar |  
  | Builders Crafts & Additions (Forge) | MRHminer | buildersaddition-1.16.3-20201028b.jar |  
  | Caelus API (Forge) | TheIllusiveC4 | caelus-forge-1.16.3-2.0.0.3.jar |  
  | Champions | TheIllusiveC4 | champions-forge-1.16.3-2.0.0.1.jar |  
  | Citadel | alex1the1666 | citadel-1.4.1.jar |  
  | CleanView | LainMI | CleanView-1.16.3-v1.jar |  
  | Collective | Serilum | collective-1.16.3-1.53.jar |  
  | Comforts | TheIllusiveC4 | comforts-forge-1.16.3-4.0.0.1.jar |  
  | Corpse Complex | TheIllusiveC4 | corpsecomplex-forge-1.16.3-4.0.0.2.jar |  
  | Cosmetic Armor Reworked | LainMI | CosmeticArmorReworked-1.16.3-v1.jar |  
  | Crafting Automat | Loldoggy | CraftingAutomat-MC1.16.3-1.2.2.jar |  
  | Cucumber Library | BlakeBr0 | Cucumber-1.16.3-4.1.3.jar |  
  | Curio of Undying (Forge) | TheIllusiveC4 | curioofundying-forge-1.16.3-5.0.0.1.jar |  
  | Curios API (Forge) | TheIllusiveC4 | curios-forge-1.16.3-4.0.2.0.jar |  
  | Curious Elytra (Forge) | TheIllusiveC4 | curiouselytra-forge-1.16.3-4.0.0.1.jar |  
  | Curious Shulker Boxes (Forge) | TheIllusiveC4 | curiousshulkerboxes-forge-1.16.3-4.0.0.1.jar |  
  | Cursed | DarkhaxDev | Cursed-1.16.3-4.0.2.jar |  
  | Dad's Sewing | dad_navi | dads_sewing-6.0.jar |  
  | Damage Tilt | Charles445 | DamageTilt-1.16-forge-0.1.1.jar |  
  | Direbats (Forge) | andantet | direbats-1.0.0+1.16.3-forge.jar |  
  | Double Slabs | CJMinecraft01 | DoubleSlabs-1.16-3.4.10.jar |  
  | Dramatic Doors | FizzWare | DramaticDoors-1.16.3-1.1.0.jar |  
  | Dungeon Crawl | XIROC1337 | DungeonCrawl-1.16.3-2.1.1.jar |  
  | Dungeons Plus | ModdingLegacy | dungeons-plus-1.16.3-1.0.3.jar |  
  | Easy Elytra Takeoff | Serilum | easyelytrato_1.16.3_1.5.jar |  
  | Enchantment Descriptions | DarkhaxDev | EnchantmentDescriptions-1.16.3-5.0.1.jar |  
  | Extended Bone Meal | Serilum | extendedbonemeal_1.16.3_1.1.jar |  
  | Extra Trades | CAS_ual_TY | extratrades-1.16.3-1.1.jar |  
  | Fairy Lights | pau101 | fairylights-4.0.0-1.16.3.jar |  
  | FallingTree | RakSrinaNa | FallingTree-Forge-1.16.3-2.5.0.jar |  
  | Farmer's Delight | vectorwing | FarmersDelight-1.16.3-0.2.3.jar |  
  | Fixed Anvil Repair Cost | Serilum | fixedanvilrepaircost_1.16.3_1.1.jar |  
  | Fusion | skrallexy | Fusion-1.16.3-2.7.0.1.jar |  
  | GildedArmor | MaroonShaded | gildedarmor-1.16.3-1.0.3.jar |  
  | Goblin Traders | MrCrayfish | goblintraders-1.2.2-1.16.3.jar |  
  | Golden Hopper | MrCrayfish | goldenhopper-1.1.1-1.16.3.jar |  
  | Good Night's Sleep | ModdingLegacy | good-nights-sleep-1.16.3-1.2.8.jar |  
  | GravelMiner | BlayTheNinth | GravelMiner_1.16.3-10.2.0.jar |  
  | Grindstone Sharper Tools | Serilum | grindstonesharpertools_1.16.3_1.4.jar |  
  | Guard Villagers | almightytallestred | guardvillagers-1.16.3-1.1.5.jar |  
  | Horse Statistics | nero_surfing | horsestatsmod-MC1.16.x-1.3.0.jar |  
  | Ice and Fire: Dragons | alex1the1666 | iceandfire-2.1.1-1.16.3.jar |  
  | Inventory Spam | gigaherz | InventorySpam-1.16.2-1.2.5.jar |  
  | Just Enough Items (JEI) | mezz | jei-1.16.3-7.6.0.51.jar |  
  | Just Mob Heads | Serilum | justmobheads_1.16.3-3.7.jar |  
  | Just Player Heads | Serilum | justplayerheads_1.16.3_1.4.jar |  
  | Lava Monsters | ModdingLegacy | lava-monster-1.16.3-1.0.9.jar |  
  | Ma Enchants | Maciej916 | Ma-Enchants-1.16.3-3.5.0.jar |  
  | Macaw's Bridges | sketch_macaw | mcw-bridges-1.0.4-mc1.16.3.jar |  
  | Macaw's Doors | sketch_macaw | mcw-doors-1.0.1fix-mc1.16.3-1.16.2.jar |  
  | Macaw's Windows | sketch_macaw | mcw-windows-1.0.2-mc1.16.3.jar |  
  | Magma Monsters | Kashdeya | MagmaMonsters-0.5.0b.jar |  
  | Miner's Helmet | ModdingLegacy | mining-helmet-1.16.3-1.1.1.jar |  
  | Mooshroom Tweaks | Serilum | mooshroomtweaks_1.16.3_1.2.jar |  
  | Mutant Beasts | Chumbanotz | MutantBeasts-1.16.3-1.1.2.jar |  
  | Naturally Charged Creepers | Serilum | nccreepers_1.16.3_1.2.jar |  
  | NetherPortalFix | BlayTheNinth | NetherPortalFix_1.16.3-7.2.1.jar |  
  | Never Break | CJMinecraft01 | NeverBreak-1.16-0.2.1.jar |  
  | Night Terror | Nuparu00 | nightterror-1.0.jar |  
  | Nutritious Milk | Serilum | nutritiousmilk_1.16.3_1.2.jar |  
  | Overloaded Armor Bar | tfarecnim | overloadedarmorbar-5.1.0.jar |  
  | Pickle Tweaks | BlakeBr0 | PickleTweaks-1.16.3-5.1.3.jar |  
  | Placeable Blaze Rods | Serilum | placeableblazerods_1.16.3_1.0.jar |  
  | Placebo | Shadows_of_Fire | Placebo-1.16.3-4.3.3.jar |  
  | Polymorph (Forge) | TheIllusiveC4 | polymorph-forge-1.16.3-0.15.jar |  
  | Premium Wood | ModdingLegacy | premium-wood-1.16.3-1.3.2.jar |  
  | Quark | Vazkii | Quark-r2.4-274.jar |  
  | RandomPatches | TheRandomLabs | randompatches-1.16.2-1.22.1.2.jar |  
  | Regrowth | MacTso | Regrowth-1.16.2-1.16.3-1.21.0.14.jar |  
  | Scuba Gear | ModdingLegacy | scuba-gear-1.16.3-1.0.1.jar |  
  | Server Tab Info | black_dog20 | ServerTabInfo-1.16.3-1.3.3.jar |  
  | SimpleCore API | skrallexy | SimpleCoreLib-1.16.3-2.0.1.2.jar |  
  | SimpleOres | skrallexy | SimpleOres2-1.16.3-2.3.1.0.jar |  
  | Skeleton Horse Spawn | Serilum | skeletonhs_1.16.3-1.4.jar |  
  | Snow Under Trees | bl4ckscor3 | snowundertrees-1.16.3-v1.1.2.jar |  
  | Spiders 2.0 | TheCyberBrick | spiders-2.0-1.16.3-1.0.4.jar |  
  | Straw Golem Reborn | CommodoreThrawn | strawgolem-1.16-1.9.jar |  
  | Structure Gel API | ModdingLegacy | structure-gel-api-1.16.3-1.6.0.jar |  
  | The Conjurer | ModdingLegacy | the-conjurer-1.16.3-1.0.13.jar |  
  | Tool Belt | gigaherz | ToolBelt-1.16.3-1.15.2.jar |  
  | Tool Stats | DarkhaxDev | ToolStats-1.16.3-4.0.1.jar |  
  | ToroHealth Damage Indicators | ToroCraft | torohealth-1.16.3-forge-4.jar |  
  | Trample Stopper | UnRealDinnerbone | TrampleStopper-2.4.3.jar |  
  | Transcending Trident | Serilum | transcendingtrident_1.16.3_1.3.jar |  
  | Unbreakable Spawner | Lothrazar | unbreakables-1.16.2-1.0.0.jar |  
  | Underwater Enchanting | Serilum | underwaterench_1.16.3_1.1.jar |  
  | Valhelsia Structures | ValhelsiaTeam | valhelsia_structures-16.0.5.jar |  
  | VanillaTweaks | StrikerRocker | VanillaTweaks-1.16.4-1.5.34.jar |  
  | Villager Death Messages | Serilum | villagerdeathm_1.16.3_1.5.jar |  
  | Villager Names | Serilum | villagernames_1.16.3-2.5.jar |  
  | Weapon Throw | dainxt | WeaponThrow-1.16.X-3.0.jar |  
  | Wither Skeleton Tweaks | Shadows_of_Fire | Wither-Skeleton-Tweaks-1.16.3-5.2.1.jar |  
  | Wizard Staff | vemerion | wizardstaff-1.16.3-1.1.0.jar |  
  | Xaero's Minimap | xaero96 | Xaeros_Minimap_20.27.2.1_Forge_1.16.4.jar |  
  | Xaero's World Map | xaero96 | XaerosWorldMap_1.11.0.1_Forge_1.16.4.jar |  
  | XP From Harvest | ReaIGecko | XPFromHarvest-1.16.3-1.2.1.jar |  
  | YUNG's Better Caves (Forge) | YUNGNICKYOUNG | BetterCaves-1.16.2-1.0.4.jar |  
  | YUNG's Better Mineshafts (Forge) | YUNGNICKYOUNG | BetterMineshaftsForge-1.16.2-1.0.1.jar |  
  | Zombie Horse Spawn | Serilum | zombiehs_1.16.3-2.5.jar |  
  | Zombie Proof Doors | Serilum | zombieproofdoors_1.16.3_1.0.jar

**Comment by xyroc** [comment]
Do you get any errors in the log when you find such a dungeon?

**Comment by Thombias** [comment]
Sorry for taking so long to respond, had a rough week.

Unfortunately the log doesn't spit out any warnings or errors when generating a dungeon. 
It simply says "Building a dungeon at x" and "Created the dungeon layout for x" as if everythings fine.

I gave the vanilla spawners config option a try but the stone blocks are still there, so the custom mob spawners aren't to blame here. Some other mod i have has to be causing this issue, but i have absolutely no idea which one. Figuring out which mod is responsible would take forever with those 115+ mods installed, so unless you may find a solution i'll just configure the mod to not use spawners, and let the mod just spawn much more mobs in the dungeons during generation instead.

Also, i've tried mod version 2.2.0 which you just released. It's kinda broken, and by that i mean it doesn't let me generate worlds because there's apperently something wrong with the datapack in the mod or so. Should i open a new issue for this and include a log? (I'm still using forge-34.1.25 btw, does 2.2.0 require a newer forge version?)

**Comment by xyroc** [comment]
>  It simply says "Building a dungeon at x" and "Created the dungeon layout for x" as if everythings fine.

That does not mean the dungeon has been generated in the world already though. To make sure that the dungeon got generated, teleport to a location near it (less than ~100 blocks distance). 

Do you get any errors in the log after teleporting to such a dungeon? I'm asking again because stone blocks instead of spawners sounds like some error occurred whilst the mod tried to place a spawner.

Are there any datapacks that modify the mod's data?

Also, it would be nice if the modpack is accessible somehow (preferably curseforge) so that i can reproduce the issue. Downloading over 100 mods manually wouldn't be my first choice.

**Comment by Thombias** [comment]
I get no errors or warnings when i teleport to such a dungeon or fly near it or go inside. I have no datapacks besides the ones that are already included in the mods i use. The modpack isn't available on cursefurge as it is still fairly early WIP. I would say it's in a pre-alpha state right now. I haven't done any configuration work as i'm still waiting for some mods to get updated, and i am also waiting for replacements of some mods that i used on my 1.12.2 modpack. (Mods that make it possible for me to configurable ore generation, and the ability to fully change all stats of every single item, be it tools, weapons or armors for balancing purposes.)

I guess i could provide you a download of my entire mods folder, but i don't know how safe that is. (Some mod creators have quite strict policies and i'd rather not get in trouble for this) Also that file would be about 64 Megabytes in size.

**Comment by Thombias** [comment]
I finally found the mod! Yesterday i had a suspicion that it could be the Unbreakable Spawner mod, as it's literally the only mod in my WIP modpack that changes spawners. So i removed said mod and guess what? The spawners are working!

Apparently even simple things like making the spawners unbreakable and nothing else, makes them not generate in the dungeons.

You may want to add that information on the curseforge page, so that other users won't have to deal with the same issue as i have. Or better yet, put an information on the page that says that you shouldn't use any mod that changes spawners in some way or form. Because like i said, even nondescript changes will break mob spawner generation.

I guess i can close this issue now, as the actual issue has finally been found.
