### ISSUE TITLE
1.14.4 Server crash with dungeoncrawl + apothesis

### ISSUE THREAD

**Issue by zEpiixz** [xyroc/DungeonCrawl#5]
https://pastebin.com/7zVyyfEm

crashed while exploring

**Comment by stillg0ld** [comment]
Did you alter the loot tables by any chance? I had the same crash after tweaking loot values and missing a bracket in the config. Didn't have any issue afterwards and I'm also using apotheosis.

**Comment by zEpiixz** [comment]
Actually no i didnt alter anything. Maybe the mod extra caves does that by itself but i just added mods ^^

**Comment by xyroc** [comment]
It looks like some very rare issue caused by two structures getting generated at the same time in the same place. At least thats my guess. I've added some safety checks in the latest update so it should at least not crash if that does happen again...
