### ISSUE TITLE
Game is soft-killed when traveling to certain location

### ISSUE THREAD

**Issue by Hiranus** [xyroc/DungeonCrawl#51]
**Observed Behaviour**
When checking my currently generated world I found area that "soft kills" MC. I can still move around, but I can't attack any mob, can't receive any damage, no chunks will be generated or loaded. When I try to break block nothing is dropped, and snow as well as grass are just "floating". Similar with gravel and TNT. See attached pictures.
If I try to save and quit game is stuck in never ending "Saving world".
If I remove any of the mods mentioned below area that cause this issue works normally, but its impossible to confirm that it is fixed, as I suspect that generation slightly changes and problematic "something" is moved to different location.

Crash log: 
https://pastebin.com/Fdca0kZ4
https://pastebin.com/HUCYnFnK
One of the mods mentions minecraft:bigdungeon, but i couldn't find it in sources of mentioned mods.
I know that there is no clear "error". Nothing else is generated in log.

**Expected Behaviour**
Problematic area works normally. I expect its issue with some dungeon generated by this mod/this combination of mods.

**Minimal setup needed to reproduce**
- Forge version: 1.15.2 - 31.2.46
- Mod configuration: default, I didn't change anything.
- Mods required to reproduce: 
astralsorcery-1.15.2-1.12.11
BiomesOPlenty-1.15.2-10.0.0.366-universal
curios-FORGE-1.15.2-2.0.2.6
DungeonCrawl-1.15.2-2.2.1
mgui-1.15.2-2.1.1
observerlib-1.15.2-1.3.1
tetra-1.15.2-2.18.1

**Steps to reproduce**
seed: 157733132531422357
X: 400
Y: 120
Z: 800

Create world with those mods, seed and travel to specified coordinates. I just do /tp 200 120 600 and fly there.

![image](https://user-images.githubusercontent.com/6943031/99130077-a5070e00-260f-11eb-8cf6-1899f48c8d03.png)
![2020-11-14_10 56 46](https://user-images.githubusercontent.com/6943031/99145003-2f309000-266b-11eb-9c34-ce31a3818316.png)

**Comment by Hiranus** [comment]
I couldn't reproduce it without Astral Sorcery and Tetra so I created bug reports there too.
https://github.com/mickelus/tetra/issues/239
https://github.com/HellFirePvP/AstralSorcery/issues/1452

**Comment by Hiranus** [comment]
@XYROC  I reproduced it on same seed but with many more mods and in different location. Do you want me to check anything special while game is still frozen? 
I also thought that its similar to https://github.com/XYROC/DungeonCrawl/issues/42 but I couldn't find any tripwires anywhere.

**Comment by xyroc** [comment]
There is no need for you to check anything while the game is frozen right now.
