### ISSUE TITLE
Server crash when entering a chunk with a dungeon (1.16.4)

### ISSUE THREAD

**Issue by baysupercool** [xyroc/DungeonCrawl#52]
Forge version: 35.0.18

A server crash happens whenever I enter a chunk with a dungeon.
I recently changed the config so dungeons will generate solid. (I'm playing with Yung's Better Caves.)

[crash-2020-11-16_18.24.51-server.txt](https://github.com/XYROC/DungeonCrawl/files/5548290/crash-2020-11-16_18.24.51-server.txt)

**Comment by xyroc** [comment]
That is a weird crash. Are you using any datapacks?

**Comment by baysupercool** [comment]
No I have no datapacks.
Also here is my config file:
[dungeon_crawl.txt](https://github.com/XYROC/DungeonCrawl/files/5548693/dungeon_crawl.txt)

**Comment by baysupercool** [comment]
I recently did some more testing only with Dungeon Crawl, here is a log from my most recent test:
[latest.log](https://github.com/XYROC/DungeonCrawl/files/5560152/latest.log)

**Comment by xyroc** [comment]
Should be fixed in version 2.2.2
