### ISSUE TITLE
Return many mobs how settings please

### ISSUE THREAD

**Issue by Sanysvo** [xyroc/DungeonCrawl#54]
Hello, I loved your mods, but we play on 2.1.1 versions because we like hardcore and many many many mobs. Can you add in config this option for enable this wild spawn?))

**Comment by Sanysvo** [comment]
Any help me?

**Comment by xyroc** [comment]
The high spawn rates in the older versions were actually caused by a bug, but I agree that the current dungeons are too easy. You can actually increase the spawnrates yourself with a datapack though. If you wish to do that, I'll gladly tell you how to!

**Comment by Sanysvo** [comment]
oww, congrats! I am listen you)

**Comment by Sanysvo** [comment]
??
