### ISSUE TITLE
[Question] Any ways to get dungeons generating in an already existing world?

### ISSUE THREAD

**Issue by Gbergz** [xyroc/DungeonCrawl#59]
Title^

Is there a way to get DungeonCrawl dungeons generating in an already existing world? (Adding the mod when the world has already been generated a little bit.)

I've tried in a fresh world, there the dungeons can be located easily with the ``/locate`` command. 
But on the existing world no dungeons can be located, meaning they don't actually spawn in(?).

**Minecraft Version:** 1.16.4
**Forge Version:** 35.1.36
**Mod Version:** [2.2.4](https://www.curseforge.com/minecraft/mc-mods/dungeon-crawl/files/3160501)

Any ideas?
**-** Gbergz

**Comment by xyroc** [comment]
The dungeons do generate in existing worlds too, but, like in any world really, only in newly generated chunks. So just explore some new areas and the dungeons should show up. Keep in mind that they currently are rather rare though.

**Comment by Gbergz** [comment]
I've explored for ages and nothing. (New chunks). Keep in mind that I have a server. Only with vanilla compatible mods on it. So vanilla clients can connect. Dungeons generate like normal on a fresh world but no Dungeons are present in the existing world. Like no where.

**Comment by Gbergz** [comment]
So..?

**Comment by xyroc** [comment]
I see, then there is probably no way to get dungeons generating in the existing world right with the current version of the mod. I will look more into it later.

**Comment by aemp222** [comment]
I'm having the same issue. I have the mod installed but no dungeons generate. However, when I use Quark with the realistic terrain generator for some reason it does generate the dungeon but it's very broken on the inside. I'm on 1.16.5 btw

**Comment by KeruMx** [comment]
Is there a way to generate dungeons in a specific place in the overworld?
