### ISSUE TITLE
More of a question then a issue I hope.

### ISSUE THREAD

**Issue by DamienNightmare** [xyroc/DungeonCrawl#61]
[crash-2021-01-25_21.50.22-client.txt](https://github.com/XYROC/DungeonCrawl/files/5871106/crash-2021-01-25_21.50.22-client.txt)

Haven't tested with the "Spawner bug fix" mainly cuz that mod doesn't seem to list "Strays" so I don,t know if this mod or some other mod is at fault here... I don't know how to read these things. Though this could also just be a forge issue cuz well beta of 16.5 soo -ima go test world with the mod-

yeah Stray spawners still break the thing... specifically breaking them.

**Comment by DamienNightmare** [comment]
ok nvm thing broke again.... Stray spanwers why Q^Q

**Comment by xyroc** [comment]
It crashed whilst trying to render a banner apparently. There is a mod called "Fabrication" installed that is messing with banner rendering, so you might want to check if removing that mod fixes the issue?

**Comment by DamienNightmare** [comment]
ohhhh.... nah i can just turn that function of the mod off i'm pretty sure
i'll close my thing once i turn it off and test it

**Comment by DamienNightmare** [comment]
ehhh im lazy ia just close it now cuz game take chunk while
