### ISSUE TITLE
Mod conflict, dungeon crawl's spawners fail to generate

### ISSUE THREAD

**Issue by nodvick** [xyroc/DungeonCrawl#64]
Dungeon crawl 1.16.3-2.2.4  minecraft version 1.16.5 single player mod conflict,

When unbreakable spawner mod is installed, the spawners fromd ugnen crawl fail to generate, all other mods that I'm currently using that have spawners generate fine. Also reported this as an issue to them. 

https://i.imgur.com/lVIMWLv.png  

the block that would have been there had dungeoncrawl not been installed is instead still there.

that mod supposedly just changed the hardness of the spawner block

reported to them at:    https://github.com/Lothrazar/UnbreakableSpawner/issues/3

EDIT: Interestingly... the crypt spawners do still spawn ( the multy-spawner room with the smoothstone and chiseled stone bricks on levels 3 and 4)

**Comment by xyroc** [comment]
Do you get any errors in the log during the world gen?

**Comment by nodvick** [comment]
No errors related to dungeon crawl in any of my logs. I do know the unbreakablespawners mod supposedly sets the hardness of the spawner on generation though, but other than being initialized their mod doesn't seem to throw any logs at all.
