### ISSUE TITLE
CTD when something spawns

### ISSUE THREAD

**Issue by MilkMan1776** [xyroc/DungeonCrawl#67]
I'm using the latest version of this mod and on the latest release of forge. This CTD occurs around skeleton spawners,
Crash Log:

The game crashed whilst rendering entity in world
Error: java.lang.ClassCastException: net.minecraft.client.renderer.WorldRenderer$$Lambda$11993/699921062 cannot be cast to net.minecraft.client.renderer.IRenderTypeBuffer$Impl
Exit Code: -1

**Comment by xyroc** [comment]
Are you using any other mods? I doubt that Dungeon Crawl is responsible for that crash.

**Comment by MilkMan1776** [comment]
I'm using a ton of mods, i'll have to test it.

**Comment by MilkMan1776** [comment]
Seems to be a problem with Optifine : /

**Comment by MilkMan1776** [comment]
Ok so it's not optifine

**Comment by MilkMan1776** [comment]
I found out what mod is causing the crashes
https://www.curseforge.com/minecraft/mc-mods/forgery

Causes a CTD around skeleton spawners as far as I know
Same Crash log as last time:

The game crashed whilst rendering entity in world
Error: java.lang.ClassCastException: net.minecraft.client.renderer.WorldRenderer$$Lambda$6429/1052117080 cannot be cast to net.minecraft.client.renderer.IRenderTypeBuffer$Impl
Exit Code: -1

**Comment by MilkMan1776** [comment]
Forgery was actually a false positive. So i'm really in the dark as to what mod it could be.
