### ISSUE TITLE
Spawners crash my game

### ISSUE THREAD

**Issue by gobbs02** [xyroc/DungeonCrawl#68]
I had to turn the spawners off, whenever i started to break a zombie spawner(specifically a zombie one, others were okay) it crashes my game, does spawnerbugfix fix this too?

**Comment by gobbs02** [comment]
[crash-2020-03-28_13.58.48-client.txt](https://github.com/XYROC/DungeonCrawl/files/6127598/crash-2020-03-28_13.58.48-client.txt)

crash log

**Comment by xyroc** [comment]
The Bountiful Baubles mod seems to be the one causing the crash.
