### ISSUE TITLE
Spawners cause CTD

### ISSUE THREAD

**Issue by MilkMan1776** [xyroc/DungeonCrawl#69]
*New issue because the old post was a mess
There was another post about spawners causing a CTD. Specifically around Zombie spawners. I'm having the same issue with skeleton spawners.

**Comment by MilkMan1776** [comment]
Crash Log:

[crash-2021-03-14_00.16.12-client.txt](https://github.com/XYROC/DungeonCrawl/files/6136146/crash-2021-03-14_00.16.12-client.txt)

**Comment by xyroc** [comment]
Have you tried removing Fabrication? The crash happens during banner rendering and it looks like Fabrication is involved.

**Comment by MilkMan1776** [comment]
I'll try disabling hi-res banners and see if that makes a difference

**Comment by MilkMan1776** [comment]
Disabling full-res banner shields fixed the problem.
Thanks!
