### ISSUE TITLE
[Suggestion] Mine and Slash compatible loot pool

### ISSUE THREAD

**Issue by Felinaxo** [xyroc/DungeonCrawl#7]
So i've started playing with a group of Friends we found this amazing mod, but when doing a test run we found out that the Loot pools are custom, therefore, we didnt get any loot related to Mine and Slash, where weapons that are even level 1 are stronger than the avarage Vanilla sword… The enemies are no issue since those scale with the leveling system in Mine and Slash, but the Loot (Mostly weapons and Armor) are rendered useless by most of Mine and Slash content.

So what im suggesting is a Mine and Slash compatible version for the mod if posible; I really think those 2 mods could go really well together, and this is the only Little push it is missing to work perfectly

Mine and Slash: https://www.curseforge.com/minecraft/mc-mods/mine-and-slash-reloaded

An example of how a level 7 common sword has far greater stats than dungeon loot:
![Sword comparation](https://user-images.githubusercontent.com/35781538/68534134-8f317f80-030f-11ea-9cfd-eb43fb8a6a24.png)

**Comment by XYROC** [comment]
Im will probably release an addon for mine and slash loot pools together with the 1.6.0 update.
