### ISSUE TITLE
Server hang/come to stop when generating dungeon - still an issue?

### ISSUE THREAD

**Issue by sprocketaudio** [xyroc/DungeonCrawl#71]
Hi I am getting server hang for over 10 mins when generating dungeons. ATM6, Mod Version 2.2.4

I havent including the entire 10 minutes of it genertaing a dungeon as there is tonnes of it! but here is the last part just before crash.

https://pastebin.com/k6sWh8q5

Sems to still n e the same issues as

https://github.com/XYROC/DungeonCrawl/issues/53

**Comment by xyroc** [comment]
Could you give me the seed of the world and the coordinates of where it happens? That would be very helpful.
