### ISSUE TITLE
[Feature Request] Option for removing rare hidden emerald block rooms

### ISSUE THREAD

**Issue by yungnickyoung** [xyroc/DungeonCrawl#74]
Hey! First of all, I love the mod. Seriously beautiful dungeons that work remarkably well with other underground mods.

I'd like if there were a config option for removing the rare room that contains several rows of emerald blocks and an end chest. I'm developing a modpack, and that much emerald in one place is quite OP, plus the End Chest slightly breaks progression.

Room in question:
![](https://i.imgur.com/8XA63YO.png)

My apologies if this has already been addressed. I didn't see anything for it in the config.

**Comment by xyroc** [comment]
Hey! The config now has an option called "secret_rooms" which you can set to false to prevent secret rooms from generating. I also have updated that room and removed most of the emerald blocks (two blocks remaining to be specific) and the ender chest.
