### ISSUE TITLE
[1.16.5] Feature Placement Crash

### ISSUE THREAD

**Issue by cyantifical** [xyroc/DungeonCrawl#75]
Exploring a world, had this mod since it was generated but a couple other mods have changed along the way, nothing world-gen based though. When exploring a snowy plains, game froze unexpectedly and produced this crash log: https://pastebin.com/qJ5Sg4aL

If it's relevant, I had another feature placement crash from blood magic with the same mods (give or take a few), so maybe its an interaction with another mod? Blood magics was apparently a conflict with scalinghealth (which is still present in this pack), but was fixed in dev for bloodmagic. Here is the blood magic issue: https://github.com/WayofTime/BloodMagic/issues/1795

**Comment by xyroc** [comment]
What other mods are you using? I haven't been able to narrow down a cause for this crash so far, but I think it must be another mod that interferes with how items are saved.

**Comment by cyantifical** [comment]
Hey, modlist can be found [here](https://www.curseforge.com/minecraft/modpacks/pathways/relations/dependencies), and when you say items being saved a couple come to mind: openloader, crafttweaker (with custom loot and recipe scripts, which work fine functionally in game), and custom starting gear.

**Comment by xyroc** [comment]
Are you able to reproduce this crash?
