### ISSUE TITLE
Subterranean compatibility

### ISSUE THREAD

**Issue by Krampus69** [xyroc/DungeonCrawl#76]
Hello,
![2021-05-15_06 56 44](https://user-images.githubusercontent.com/81943963/118348492-fbb3bd00-b54a-11eb-89d6-52b1293155a3.png)
This is a great mod, but coupled with Subterranean Wilderness it just behaves badly. As you can see on this picture, the dungeon is covered with subwild decoration.
Would be nice to not have all this fluff, especially the vines;
Thanks for your work and awesome mod :)

**Comment by XYROC** [comment]
Is this the 1.16 version of Dungeon Crawl?

**Comment by Krampus69** [comment]
Hi,
I forgot some infos : 
This is the DungeonCrawl-1.16.3-2.2.4 version
subwild-1.2.1

All running on a 1.16.5 Forge 36.1.4 version
