### ISSUE TITLE
Dungeon Crawl worldgen error: "/locate command dungeoncrawl:dungeon" doesn't work

### ISSUE THREAD

**Issue by Nekkok** [xyroc/DungeonCrawl#79]
The mod doesn't work at all. Neither the command to find the structures, nor to find them in spectator mode. I may suppose it conflicts with other mods, like Yung's Better Caves / Mineshafts, Repurposed Structures and When Dungeons Arise, as they all change the overworld below. Also BGcore is installed.

Minecraft version: 1.16.5
Forge version: 36.1.24
Mod version: DungeonCrawl-1.16.3-2.2.4

**Comment by Nekkok** [comment]
I found the culprit: William Wither's Overworld Overhaul datapack seems not be compatible with it.

**Comment by Wedge1453** [comment]
I have the same problem, if I use /locate the game semi freezes (I can move around tho) and the only way I can close minecraft is by killing the task.
using this modpack: https://www.curseforge.com/minecraft/modpacks/reform

**Comment by WordStormRose** [comment]
I also have this same problem, though from time to time it just crashes on its own thanks to a single tick taking a long time. I am using my modpack Lennbain: https://www.curseforge.com/minecraft/modpacks/lennbain 

Minecraft version 1.16.5
Forge version 36.1.42
Mod version 2.2.4

Edit: Seems that removing BGCore makes the dungeons spawn again; I'm going to leave an issue report on their page as well in case it isn't something that you can fix.

**Comment by harmalom** [comment]
did you manage to solve this?, because I have the same problem that the dungeonCrawl does not spawn, and I do not have BGCore installed.

**Comment by WordStormRose** [comment]
I did not find a way on my end, but blackgear (mod author of BGCore) has said that they're looking into it.

**Comment by Jukabofy** [comment]
They need obligatory, Spawner bug fix mod, It solve the problem, I mean the same issue was solved just installing the other mod
