### ISSUE TITLE
[1.14.4] Structure.hasStartAt somehow trying to instantiate array with negative size

### ISSUE THREAD

**Issue by noobanidus** [xyroc/DungeonCrawl#8]
See [crash report here](https://github.com/XYROC/DungeonCrawl/blob/1.14.4/src/main/java/xiroc/dungeoncrawl/dungeon/Dungeon.java#L92).

It appesrs that the Dungeon::hasStartAt is using very similar code to say, the Woodland Mansion, on 95 and 96: 

```
	for (Biome biome : chunkGen.getBiomeProvider().getBiomesInSquare(chunkPosX * 16 + SIZE / 2 * 8,
					chunkPosZ * 16 + SIZE / 2 * 8, 8 * SIZE)) {

```

However, in this instance, going through the different calls, the crash is occurring at line 21 of Layer.java, in `generateBiomes`: `Biome[] abiome = new Biome[xSize * zSize];`

The implication here is that, somehow, `xSize * zSize` (which is derived from some bit shifting within `getBiomesInSquare`, and then initially from the `centerX/centerZ` + `sideLength` passed in as per above, is resulting in a negative value, which is then being used to instantiate an array.

I'm not sure of the different values that you're using, thankfully the crash report actually have the relevant chunks and region information that might be able to help you back-trace the error.

**Comment by xyroc** [comment]
Okay, thank you for the information. However, the link you provided seems to lead to the _Dungeon#hasStartAt_ function in the code and not to the crash report. :)

**Comment by noobanidus** [comment]
My bad, I was failing to multitask. [This should be the correct link](https://gist.github.com/duely/71447a44816536f0e1b0fd85cdd99168)
