### ISSUE TITLE
[1.17.1] Forge update broke mod during world generation, locating a dungeon crashes the game.

### ISSUE THREAD

**Issue by Gbergz** [xyroc/DungeonCrawl#83]
^ Forge update broke mod during world generation, locating a dungeon crashes the game. ^

Might have something to do with this forge update: (not sure), it works fine on .21
```
Build: 1.17.1-37.0.22 - Mon Aug 02 22:47:24 GMT 2021
	hycrafthd:
		Rename potion registry fields to match the mojang names (#7939)
```

### Versions:
**Minecraft:** 1.17.1
**Forge:** 37.0.25
**Dungeon Crawl:** [2.3.0](https://www.curseforge.com/minecraft/mc-mods/dungeon-crawl/files/3405172)

**Crash-Report**: https://gist.github.com/Gbergz/868a290f20fedf02e052b2a43a4aa1b9

**-** Gbergz

**Comment by xyroc** [comment]
Thank you for the report! A version with the fix is available on curseforge now.
