### ISSUE TITLE
ConcurrentModificationException during spawner placement

### ISSUE THREAD

**Issue by forebordingsky** [xyroc/DungeonCrawl#88]
Crash log
[crash-2021-08-08_20.09.31-client.txt](https://github.com/xyroc/DungeonCrawl/files/6953033/crash-2021-08-08_20.09.31-client.txt)

**Comment by xyroc** [comment]
Are you sure this is related to TerraForged?

**Comment by forebordingsky** [comment]
Description: generating features & structures (TerraForged World-Gen)

com.terraforged.mod.profiler.watchdog.UncheckedException: Critical error detected whilst generating Structure dungeoncrawl:dungeon

**Comment by forebordingsky** [comment]
It's not always crashes, but very frequently. After relog, world loads normally.

**Comment by Won-Ton** [comment]
> Are you sure this is related to TerraForged?

[I took a look already](https://github.com/TerraForged/tracker/issues/143#issuecomment-894828164). It isn't anything to do with TF. Only thing that stands out to me is the number of mods coremodding/mixin'ing the itemstack/nbt stuff between your structure code and the eventual CME. I wouldn't know where to start trying to pick that apart though unfortunately.
