### ISSUE TITLE
Can't Find Loot Table File

### ISSUE THREAD

**Issue by Tinn04** [xyroc/DungeonCrawl#89]
I've been searching through the config files and have not been able to find the files that include the loot table. In the image below are all the files relating to DungeonsCrawl in the configs.
<img width="755" alt="Screen Shot 2021-08-16 at 10 00 22 PM" src="https://user-images.githubusercontent.com/69121624/129666329-5940190e-06cc-4489-9c53-cf7a7f17a05c.png">
Am I not seeing something? And how would I edit the loot table if I do manage to find the file?

**Comment by xyroc** [comment]
The loot tables are part of Dungeon Crawl's default datapack. [You can learn more about datapacks here](https://minecraft.gamepedia.com/Data_Pack).
