### ISSUE TITLE
Feature Placement causes World-Breaking Crash

### ISSUE THREAD

**Issue by oitsjustjose** [xyroc/DungeonCrawl#9]
Heya! I'm in love with this mod, but it's cost me my server world so I thought I'd put in a report.

## Versions

Minecraft: 1.14.4
Forge: 28.1.90
DC: 1.5.1

## Crash Log

[Found here](https://gist.github.com/oitsjustjose/e727e5c4087d2cd90956f458851f681f#file-crash-log-L1314-L1446).

_____

I'm not sure if this has been fixed in any of your recent commits -- it didn't seem so, but I could be wrong. Let me know if you need any more info!

**Comment by xyroc** [comment]
Thank you for the report! :) The latest DC version (1.5.2), which i've just uploaded, should hopefully fix that.
