### ISSUE TITLE
Ticking entity crashing server 

### ISSUE THREAD

**Issue by stradar21** [xyroc/DungeonCrawl#99]
Using Forge 1.17.1 version 37.0.84

your mod version DungeonCrawl-1.17.1-2.3.2

I am using other mods. All day yesterday friends raiding your dungeons I noticed constant amounts of Ticking Entity crashing.

Had something to do with Wither Skeletons. I have a crash report hopefully u can help me figure out why this is happening.

I also noticed spawners spawning in a crap loads of mobs in the dungeon.

[crash-2021-10-18_01.01.01-server.txt](https://github.com/xyroc/DungeonCrawl/files/7365606/crash-2021-10-18_01.01.01-server.txt)

**Comment by stradar21** [comment]
Any news on this?

**Comment by xyroc** [comment]
Well, I doubt that dungeon crawl is the mod at fault here. All it does is give wither skeletons a custom loot table (if not disabled in the config), and therefore I suppose that another mod broke something related to that.
The log shows that citadel, expandability and serene seasons are using mixins that modify entity code. The log also shows that the entity was trying to select its next goal (=AI choosing what to do next), so if you have any mods that mess with mob AI, consider removing those to see if that fixes the issue.

**Comment by stradar21** [comment]
Thank you for getting back with me. I don't know which mod that is messing with mob Ai but I do know spawners is whats causing issues so I dunno which mod that is causing loads of mob spawns but looking into that.

**Comment by simplyskellix** [comment]
have the same issue! right now I've narrowed it down to a small list of mods and dungeon crawl is one of them. the ticking entity crash only happens when fighting wither skeletons with thorns OR guardians. I'm looking more into the issue and will add an edit to my response if I come across anything else or can specifically determine if it is this mod or an incompatibility.
